[build]
  command = "npm run build"
  publish = ".next"
  ignore = "exit 1"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[build.environment]
  NEXT_PUBLIC_API_URL = "https://newsportal-backend.happyglacier-db0dd319.westeurope.azurecontainerapps.io"
  NODE_VERSION = "20"

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

[[redirects]]
  from = "/api/*"
  to = "https://newsportal-backend.happyglacier-db0dd319.westeurope.azurecontainerapps.io/api/:splat"
  status = 200
  force = true
