# ============================================
# Production Override Configuration
# ============================================
# Usage: docker-compose -f docker-compose.yml -f docker-compose.prod.yml up -d
# ============================================

services:
  newsapi:
    build:
      args:
        BUILDCONFIG: Release
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - Logging__LogLevel__Default=Warning
      - Logging__LogLevel__Microsoft=Error
    restart: always
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 512M
        reservations:
          cpus: '0.5'
          memory: 256M

  mongodb:
    restart: always
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 1G
        reservations:
          cpus: '0.5'
          memory: 512M

  minio:
    restart: always
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512M
        reservations:
          cpus: '0.25'
          memory: 256M

  # Disable Mongo Express in production
  mongo-express:
    profiles:
      - debug
