openapi: 3.0.3
info:
  title: News API
  description: Modernized .NET 8 News API with Clean Architecture
  version: 2.0.0
  contact:
    name: News API Team
    
servers:
  - url: https://localhost:5001
    description: Development server
  - url: https://haberibul.azurewebsites.net
    description: Production server

security:
  - bearerAuth: []

paths:
  /api/news:
    get:
      summary: Get all news articles
      description: Retrieve all active news articles with caching
      tags:
        - News
      security: []  # Public endpoint
      parameters:
        - name: category
          in: query
          description: Filter by category
          required: false
          schema:
            type: string
        - name: type
          in: query
          description: Filter by type (news/subNews)
          required: false
          schema:
            type: string
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/News'
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
                
    post:
      summary: Create new news article
      description: Create a new news article (requires authentication)
      tags:
        - News
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateNewsDto'
      responses:
        '201':
          description: News article created successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/News'
        '400':
          description: Validation error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ValidationErrorResponse'
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

  /api/news/{id}:
    get:
      summary: Get news article by ID
      description: Retrieve a specific news article by its ID
      tags:
        - News
      security: []  # Public endpoint
      parameters:
        - name: id
          in: path
          required: true
          description: News article ID
          schema:
            type: string
            format: uuid
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/News'
        '404':
          description: News article not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
                
    put:
      summary: Update news article
      description: Update an existing news article (requires authentication)
      tags:
        - News
      security:
        - bearerAuth: []
      parameters:
        - name: id
          in: path
          required: true
          description: News article ID
          schema:
            type: string
            format: uuid
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdateNewsDto'
      responses:
        '200':
          description: News article updated successfully
        '400':
          description: Validation error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ValidationErrorResponse'
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '404':
          description: News article not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
                
    delete:
      summary: Delete news article
      description: Delete a news article (requires authentication)
      tags:
        - News
      security:
        - bearerAuth: []
      parameters:
        - name: id
          in: path
          required: true
          description: News article ID
          schema:
            type: string
            format: uuid
      responses:
        '204':
          description: News article deleted successfully
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '404':
          description: News article not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
      
  schemas:
    News:
      type: object
      properties:
        id:
          type: string
          format: uuid
        category:
          type: string
          maxLength: 100
        type:
          type: string
          maxLength: 50
        caption:
          type: string
          maxLength: 500
        keywords:
          type: string
        socialTags:
          type: string
        summary:
          type: string
          maxLength: 1000
        imgPath:
          type: string
        imgAlt:
          type: string
        content:
          type: string
        subjects:
          type: array
          items:
            type: string
        authors:
          type: array
          items:
            type: string
        expressDate:
          type: string
          format: date-time
        createDate:
          type: string
          format: date-time
        updateDate:
          type: string
          format: date-time
        priority:
          type: integer
          minimum: 1
        isActive:
          type: boolean
        url:
          type: string
          maxLength: 500
        viewCount:
          type: integer
        isSecondPageNews:
          type: boolean
          
    CreateNewsDto:
      type: object
      required:
        - category
        - type
        - caption
        - summary
        - content
        - subjects
        - authors
        - expressDate
        - priority
        - isActive
        - url
      properties:
        category:
          type: string
          maxLength: 100
        type:
          type: string
          maxLength: 50
        caption:
          type: string
          maxLength: 500
        summary:
          type: string
          maxLength: 1000
        content:
          type: string
        subjects:
          type: array
          items:
            type: string
          minItems: 1
        authors:
          type: array
          items:
            type: string
          minItems: 1
        expressDate:
          type: string
          format: date-time
        priority:
          type: integer
          minimum: 1
        isActive:
          type: boolean
        url:
          type: string
          maxLength: 500
          
    UpdateNewsDto:
      type: object
      properties:
        category:
          type: string
          maxLength: 100
        type:
          type: string
          maxLength: 50
        caption:
          type: string
          maxLength: 500
        summary:
          type: string
          maxLength: 1000
        content:
          type: string
        subjects:
          type: array
          items:
            type: string
        authors:
          type: array
          items:
            type: string
        expressDate:
          type: string
          format: date-time
        priority:
          type: integer
          minimum: 1
        isActive:
          type: boolean
        url:
          type: string
          maxLength: 500
          
    ErrorResponse:
      type: object
      properties:
        error:
          type: string
        message:
          type: string
        statusCode:
          type: integer
          
    ValidationErrorResponse:
      type: object
      properties:
        error:
          type: string
          example: "Validation failed"
        message:
          type: string
          example: "One or more validation errors occurred"
        statusCode:
          type: integer
          example: 400
        errors:
          type: object
          additionalProperties:
            type: array
            items:
              type: string