version: '3.8'

services:
  # MinIO - S3-compatible object storage for images
  minio:
    image: minio/minio:latest
    container_name: news-api-minio
    ports:
      - "9000:9000"  # API port
      - "9001:9001"  # Web Console port
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin123
      MINIO_BROWSER_REDIRECT_URL: http://localhost:9001
    volumes:
      - minio_data:/data
    command: server /data --console-address ":9001"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3
    networks:
      - news-api-network

  # MinIO Client - For initialization
  minio-init:
    image: minio/mc:latest
    container_name: news-api-minio-init
    depends_on:
      - minio
    entrypoint: >
      /bin/sh -c "
      sleep 5;
      /usr/bin/mc alias set myminio http://minio:9000 minioadmin minioadmin123;
      /usr/bin/mc mb myminio/news-images --ignore-existing;
      /usr/bin/mc anonymous set download myminio/news-images;
      /usr/bin/mc anonymous set public myminio/news-images;
      echo 'MinIO bucket created and configured successfully';
      exit 0;
      "
    networks:
      - news-api-network

  # MongoDB - NoSQL database
  mongodb:
    image: mongo:latest
    container_name: news-api-mongodb
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin123
    volumes:
      - mongodb_data:/data/db
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - news-api-network

volumes:
  minio_data:
    driver: local
  mongodb_data:
    driver: local

networks:
  news-api-network:
    driver: bridge
