export const mockNewsArticle = {
  id: '1',
  category: 'reddit',
  type: 'news',
  caption: 'Yapay Zeka Çağında Yeni Gelişmeler',
  slug: 'yapay-zeka-caginda-yeni-gelismeler',
  keywords: 'yapay zeka, AI, GPT-5, OpenAI, teknoloji',
  socialTags: '#YapayZeka #AI #GPT5 #Teknoloji',
  summary: 'OpenAI\'nin yeni GPT-5 modeli, yapay zeka dünyasında devrim yaratmaya hazırlanıyor.',
  imgPath: 'http://localhost:9000/news-images/technology/ai-development.jpg',
  imgAlt: 'Yapay Zeka Görseli',
  imageUrl: 'http://localhost:9000/news-images/technology/ai-development.jpg',
  thumbnailUrl: 'http://localhost:9000/news-images/technology/ai-development-thumb.jpg',
  content: '<p>OpenAI, yapay zeka alanındaki en son hamlesiyle <strong>GPT-5 modelini</strong> tanıttı.</p>',
  subjects: ['Yapay Zeka', 'Teknoloji', 'İnovasyon'],
  authors: ['Ahmet Yılmaz'],
  expressDate: '2025-10-23T10:00:00Z',
  createDate: '2025-10-23T10:00:00Z',
  updateDate: '2025-10-23T10:00:00Z',
  priority: 1,
  isActive: true,
  url: '/news/yapay-zeka-caginda-yeni-gelismeler',
  viewCount: 1250,
  isSecondPageNews: false,
};

export const mockNewsArticles = [
  mockNewsArticle,
  {
    id: '2',
    category: 'github',
    type: 'news',
    caption: 'GitHub\'da Yeni Açık Kaynak Projeler',
    slug: 'github-yeni-acik-kaynak-projeler',
    keywords: 'GitHub, açık kaynak, open source, geliştirici',
    socialTags: '#GitHub #OpenSource #Geliştirici',
    summary: 'GitHub\'da bu hafta en çok yıldız alan açık kaynak projeleri ve geliştirici trendleri.',
    imgPath: 'http://localhost:9000/news-images/github/opensource-projects.jpg',
    imgAlt: 'GitHub Açık Kaynak Projeler',
    imageUrl: 'http://localhost:9000/news-images/github/opensource-projects.jpg',
    thumbnailUrl: 'http://localhost:9000/news-images/github/opensource-projects-thumb.jpg',
    content: '<p>Bu hafta <strong>GitHub\'da en popüler projeler</strong> arasında yapay zeka araçları öne çıktı.</p>',
    subjects: ['Açık Kaynak', 'GitHub', 'Yazılım Geliştirme'],
    authors: ['Geliştirici Topluluğu'],
    expressDate: '2025-10-23T08:00:00Z',
    createDate: '2025-10-23T08:00:00Z',
    updateDate: '2025-10-23T08:00:00Z',
    priority: 1,
    isActive: true,
    url: '/news/galatasaray-avrupada-tarih-yazdi',
    viewCount: 5800,
    isSecondPageNews: false,
  },
  {
    id: '3',
    category: 'twitter',
    type: 'news',
    caption: 'Twitter\'da Viral Olan Teknoloji Haberleri',
    slug: 'twitter-viral-teknoloji-haberleri',
    keywords: 'Twitter, X, sosyal medya, viral, teknoloji',
    socialTags: '#Twitter #X #SosyalMedya #Viral',
    summary: 'X/Twitter\'da bu hafta en çok konuşulan teknoloji haberleri ve trendler.',
    imgPath: 'http://localhost:9000/news-images/twitter/viral-tech.jpg',
    imgAlt: 'Twitter Viral İçerikler',
    imageUrl: 'http://localhost:9000/news-images/twitter/viral-tech.jpg',
    thumbnailUrl: 'http://localhost:9000/news-images/twitter/viral-tech-thumb.jpg',
    content: '<p><strong>X/Twitter\'da viral olan</strong> yapay zeka ve teknoloji haberleri listesi.</p>',
    subjects: ['Sosyal Medya', 'Twitter', 'Teknoloji Trendleri'],
    authors: ['Sosyal Medya Editörlüğü'],
    expressDate: '2025-10-22T15:00:00Z',
    createDate: '2025-10-22T15:00:00Z',
    updateDate: '2025-10-22T15:00:00Z',
    priority: 1,
    isActive: true,
    url: '/news/marsta-su-kesfi-yasam-izleri-bulundu',
    viewCount: 4500,
    isSecondPageNews: false,
  },
];

export const mockCategories = [
  { id: 'reddit', name: 'Reddit', count: 5 },
  { id: 'github', name: 'GitHub', count: 4 },
  { id: 'twitter', name: 'X/Twitter', count: 6 },
  { id: 'linkedin', name: 'LinkedIn', count: 3 },
  { id: 'facebook', name: 'Facebook', count: 4 },
  { id: 'instagram', name: 'Instagram', count: 5 },
  { id: 'tiktok', name: 'TikTok', count: 7 },
  { id: 'youtube', name: 'YouTube', count: 6 },
  { id: 'technology', name: 'Teknoloji', count: 8 },
];
