export const mockNewsArticle = {
  id: '1',
  category: 'technology',
  type: 'news',
  caption: 'Yapay Zeka Çağında Yeni Gelişmeler',
  slug: 'yapay-zeka-caginda-yeni-gelismeler',
  keywords: 'yapay zeka, AI, GPT-5, OpenAI, teknoloji',
  socialTags: '#YapayZeka #AI #GPT5 #Teknoloji',
  summary: 'OpenAI\'nin yeni GPT-5 modeli, yapay zeka dünyasında devrim yaratmaya hazırlanıyor.',
  imgPath: 'http://localhost:9000/news-images/technology/ai-development.jpg',
  imgAlt: 'Yapay Zeka Görseli',
  imageUrl: 'http://localhost:9000/news-images/technology/ai-development.jpg',
  thumbnailUrl: 'http://localhost:9000/news-images/technology/ai-development-thumb.jpg',
  content: '<p>OpenAI, yapay zeka alanındaki en son hamlesiyle <strong>GPT-5 modelini</strong> tanıttı.</p>',
  subjects: ['Yapay Zeka', 'Teknoloji', 'İnovasyon'],
  authors: ['Ahmet Yılmaz'],
  expressDate: '2025-10-23T10:00:00Z',
  createDate: '2025-10-23T10:00:00Z',
  updateDate: '2025-10-23T10:00:00Z',
  priority: 1,
  isActive: true,
  url: '/news/yapay-zeka-caginda-yeni-gelismeler',
  viewCount: 1250,
  isSecondPageNews: false,
};

export const mockNewsArticles = [
  mockNewsArticle,
  {
    id: '2',
    category: 'sports',
    type: 'news',
    caption: 'Galatasaray Avrupa\'da Tarih Yazdı',
    slug: 'galatasaray-avrupada-tarih-yazdi',
    keywords: 'Galatasaray, Şampiyonlar Ligi, Avrupa, futbol',
    socialTags: '#Galatasaray #ŞampiyonlarLigi #Avrupa',
    summary: 'Galatasaray, Şampiyonlar Ligi\'nde çeyrek finale yükselen ilk Türk takımı oldu.',
    imgPath: 'http://localhost:9000/news-images/sports/galatasaray-champions.jpg',
    imgAlt: 'Galatasaray Taraftarları Kutlama',
    imageUrl: 'http://localhost:9000/news-images/sports/galatasaray-champions.jpg',
    thumbnailUrl: 'http://localhost:9000/news-images/sports/galatasaray-champions-thumb.jpg',
    content: '<p>Galatasaray, Manchester City\'yi penaltılarla 5-4 yenerek <strong>Şampiyonlar Ligi çeyrek finaline</strong> yükseldi.</p>',
    subjects: ['Futbol', 'Şampiyonlar Ligi', 'Galatasaray'],
    authors: ['Avrupa Futbolu Editörlüğü'],
    expressDate: '2025-10-23T08:00:00Z',
    createDate: '2025-10-23T08:00:00Z',
    updateDate: '2025-10-23T08:00:00Z',
    priority: 1,
    isActive: true,
    url: '/news/galatasaray-avrupada-tarih-yazdi',
    viewCount: 5800,
    isSecondPageNews: false,
  },
  {
    id: '3',
    category: 'science',
    type: 'news',
    caption: 'Mars\'ta Su Keşfi: Yaşam İzleri Bulundu',
    slug: 'marsta-su-kesfi-yasam-izleri-bulundu',
    keywords: 'Mars, NASA, su, yaşam, uzay keşfi',
    socialTags: '#Mars #NASA #UzayKeşfi #Bilim',
    summary: 'NASA\'nın Perseverance rover\'ı, Mars\'ın yüzeyinin altında sıvı su izleri tespit etti.',
    imgPath: 'http://localhost:9000/news-images/science/mars-discovery.jpg',
    imgAlt: 'Mars Yüzeyi',
    imageUrl: 'http://localhost:9000/news-images/science/mars-discovery.jpg',
    thumbnailUrl: 'http://localhost:9000/news-images/science/mars-discovery-thumb.jpg',
    content: '<p>NASA\'nın <strong>Perseverance uzay aracı</strong>, Mars\'ta devrim niteliğinde bir keşif yaptı.</p>',
    subjects: ['Uzay Bilimi', 'Astrobiyoloji', 'Mars'],
    authors: ['Dr. Sarah Johnson', 'Prof. Ali Toprak'],
    expressDate: '2025-10-22T15:00:00Z',
    createDate: '2025-10-22T15:00:00Z',
    updateDate: '2025-10-22T15:00:00Z',
    priority: 1,
    isActive: true,
    url: '/news/marsta-su-kesfi-yasam-izleri-bulundu',
    viewCount: 4500,
    isSecondPageNews: false,
  },
];

export const mockCategories = [
  { id: 'technology', name: 'Teknoloji', count: 5 },
  { id: 'sports', name: 'Spor', count: 4 },
  { id: 'science', name: 'Bilim', count: 3 },
  { id: 'world', name: 'Dünya', count: 3 },
  { id: 'business', name: 'Ekonomi', count: 3 },
  { id: 'health', name: 'Sağlık', count: 2 },
  { id: 'entertainment', name: 'Eğlence', count: 3 },
];
