name: CI

on:
  push:
    branches:
      - master
      - release/*

jobs:
  build_newsApi:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Build and deploy the Docker image

        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
          APP_NAME: ${{ 'newsApi' }}
        run: |
          cd ./NEWS-API
          docker login --username=_ --password=$HEROKU_API_KEY registry.heroku.com
          heroku container:push web -a newsApi
          heroku container:release web -a newsApi
